  
name: makepkg CI

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
    branches: 
    - master
  #schedule:
  #  - cron: 00 15 * * *
  watch:
    types: [started]

jobs:
  build-arch-pkg:
    strategy:
      matrix:
        arch: ["aarch64", "x86_64"]
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.arch }}
    if: github.event.repository.owner.id == github.event.sender.id || github.event_name == 'schedule'
    env:
      UPSTREAM_URL: ${{ secrets.UPSTREAM_URL }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Pull upstream changes
      uses: atomlong/Sync-With-Upstream-action@master
      id: sync
      if: ${{ env.UPSTREAM_URL != '' }}
      with:
        upstream_repository: ${{ env.UPSTREAM_URL }}
        upstream_branch: master
        target_branch: master
        git_pull_args: --rebase
        git_push_args: --force-with-lease
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run on Archlinux
      uses: atomlong/run-on-arch-action@alarm
      id: runcmd
      if: steps.sync.outputs.has_new_commits != 'false'
      with:
        arch: ${{ matrix.arch }}
        githubToken: ${{ github.token }}
        rcloneConfig: ${{ secrets.RCLONE_CONF }}
        pgpKey: ${{ secrets.PGP_KEY }}
        pgpKeyPassword: ${{ secrets.PGP_KEY_PASSWD }}
        pacmanRepo: ${{ secrets.PACMAN_REPO }}
        deployPath: ${{ secrets.DEPLOY_PATH }}
        customRepos: ${{ secrets.CUSTOM_REPOS }}
    - name: Send build result via mail
      uses: atomlong/send-mail-action@v3.1.0
      if: ${{ steps.runcmd.outputs.message != '' }}
      with:
        server_address: ${{secrets.MAIL_HOST}}
        server_port: ${{secrets.MAIL_PORT}}
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions job of ${{github.repository}} result
        html_body: ${{ steps.runcmd.outputs.message }}
        to: ${{secrets.MAIL_TO}}
        from: Github
    - name: Send sync result via mail
      uses: atomlong/send-mail-action@v3.7.1
      if: ${{ steps.sync.outputs.error_message != '' }}
      with:
        server_address: ${{secrets.MAIL_HOST}}
        server_port: ${{secrets.MAIL_PORT}}
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions job of ${{github.repository}} result
        html_body: ${{ steps.sync.outputs.error_message }}
        to: ${{secrets.MAIL_TO}}
        from: Github
        
  build-msys2-pkg:
    runs-on: windows-latest
    if: github.event.repository.owner.id == github.event.sender.id || github.event_name == 'schedule'
    steps:
    - name: Set git to use LF
      id: gitconfig
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - uses: actions/checkout@v3
      id: checkout
      with:
        fetch-depth: 0
    - name: Run on Msys2
      uses: atomlong/run-on-msys-action@master
      id: runcmd
      with:
        rcloneConfig: ${{ secrets.RCLONE_CONF }}
        pgpKey: ${{ secrets.PGP_KEY }}
        pgpKeyPassword: ${{ secrets.PGP_KEY_PASSWD }}
        pacmanRepo: ${{ secrets.PACMAN_REPO }}
        deployPath: ${{ secrets.DEPLOY_PATH }}
        customRepos: ${{ secrets.CUSTOM_REPOS }}
    - name: Send mail
      uses: atomlong/send-mail-action@v3
      if: ${{ steps.runcmd.outputs.message != '' }}
      with:
        server_address: ${{secrets.MAIL_HOST}}
        server_port: ${{secrets.MAIL_PORT}}
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions job of ${{github.repository}} result
        html_body: ${{ steps.runcmd.outputs.message }}
        to: ${{secrets.MAIL_TO}}
        from: Github
        attachments: ${{ steps.runcmd.outputs.logs }}
        